services:
  client:
    build: ./client
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - server
    develop:
      watch:
        - action: rebuild
          path: ./client

  server:
    build: ./server
    env_file: server/.env
    ports:
      - "127.0.0.1:3001:3000"
    networks:
      - backend_network
    depends_on:
      - database
    develop:
      watch:
        - action: rebuild
          path: ./server

  database:
    image: postgres:16.0-alpine3.18
    env_file: .env.database
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - backend_network

volumes:
  database_volume:

networks:
  backend_network:
